
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you might want to handle this more gracefully.
  // For this example, we will throw an error if the API key is not set.
  // In the target environment, this variable is expected to be present.
  console.warn("API_KEY environment variable not set. Gemini API calls will fail.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

export const generatePostContent = async (prompt: string): Promise<string> => {
  if (!API_KEY) {
    console.log("Using mock response due to missing API key.");
    // Return a mock response if API_KEY is not available
    return new Promise(resolve => setTimeout(() => {
        resolve(`This is a mock AI-generated post about your prompt: "${prompt}". In a real scenario, this would be generated by the Gemini model. It would be insightful, engaging, and perfectly tailored to a social media audience.`);
    }, 1000));
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });

    const text = response.text;
    if (text) {
      return text.trim();
    } else {
      throw new Error("Received an empty response from Gemini API.");
    }
  } catch (error) {
    console.error("Error generating content with Gemini:", error);
    throw new Error("Failed to generate content from Gemini API.");
  }
};
