import { GoogleGenAI, Type } from "@google/genai";
import { Source, TrendingTopic } from "../types";

const API_KEY = process.env.API_KEY;
let ai: GoogleGenAI | null = null;

// Conditionally initialize the AI client.
// This is the critical fix to prevent the app from crashing on deployment
// when the environment variable is not set.
if (API_KEY) {
  ai = new GoogleGenAI({ apiKey: API_KEY });
} else {
  console.warn("API_KEY environment variable not set. Gemini API calls will use mock data.");
}

const systemInstruction = `You are an AI assistant for a civic engagement platform called 'Digital Democracy'. Your tone must be neutral, informative, and encouraging of constructive dialogue. Avoid partisan language, speculation, or inflammatory statements. When generating a post based on a topic, rely on the provided search results to ensure accuracy.`;

export const generatePostContent = async (topic?: string): Promise<{ text: string; sources: Source[] }> => {
  const prompt = topic 
    ? `Write a positive and engaging social media post for a political campaign about: "${topic}"`
    : `Write a positive and engaging social media post for a political campaign about improving local communities.`;
  
  // If the 'ai' client failed to initialize, return mock data immediately.
  if (!ai) {
    console.log("Using mock response due to missing API key.");
    return new Promise(resolve => setTimeout(() => {
        resolve({
          text: `This is a mock AI-generated post about "${topic || 'local communities'}". In a real scenario, this would be generated by the Gemini model, grounded in real-time search results for accuracy and credibility.`,
          sources: [
            { title: "Mock Source 1: Community News", uri: "#" },
            { title: "Mock Source 2: City Council Report", uri: "#" }
          ]
        });
    }, 1000));
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        systemInstruction,
        tools: [{googleSearch: {}}],
      }
    });

    const text = response.text;
    const groundingMetadata = response.candidates?.[0]?.groundingMetadata;
    
    let sources: Source[] = [];
    if (groundingMetadata?.groundingChunks) {
      sources = groundingMetadata.groundingChunks
        .filter(chunk => chunk.web)
        .map(chunk => ({
          title: chunk.web.title,
          uri: chunk.web.uri,
        }));
    }

    if (text) {
      return { text: text.trim(), sources };
    } else {
      throw new Error("Received an empty response from Gemini API.");
    }
  } catch (error) {
    console.error("Error generating content with Gemini:", error);
    throw new Error("Failed to generate content from Gemini API.");
  }
};

export const generateCreatorSpotlight = async (): Promise<{ quote: string; author: string; }> => {
  const prompt = `You are an AI for a civic engagement platform. Generate a short, powerful, and inspirational quote about one of the following topics: civic duty, community building, leadership, positive change, or the power of a single voice. The quote should be under 200 characters. Also, provide the name of a historical figure, philosopher, or an anonymous source (e.g., 'Ancient Proverb') to attribute the quote to.`;
  
  // If the 'ai' client failed to initialize, return mock data immediately.
  if (!ai) {
    console.log("Using mock spotlight response due to missing API key.");
    return new Promise(resolve => setTimeout(() => {
        resolve({
          quote: "The future is built by the hands of those who show up.",
          author: "A wise mock philosopher"
        });
    }, 800));
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            quote: { type: Type.STRING, description: "The inspirational quote." },
            author: { type: Type.STRING, description: "The author or source of the quote." }
          },
          required: ["quote", "author"]
        }
      }
    });

    const jsonText = response.text.trim();
    const data = JSON.parse(jsonText);
    
    if (data.quote && data.author) {
      return data;
    } else {
      throw new Error("Received invalid JSON structure from Gemini API.");
    }

  } catch (error) {
    console.error("Error generating creator spotlight with Gemini:", error);
    throw new Error("Failed to generate creator spotlight from Gemini API.");
  }
};

export const generateTrendingTopics = async (): Promise<TrendingTopic[]> => {
  const prompt = `Generate a list of 5 current, realistic trending topics for a social media platform focused on civic engagement and politics. For each topic, provide a category (e.g., "National Politics", "Community", "Technology"), the topic title, and a fictional but realistic post count.`;

  if (!ai) {
    console.log("Using mock trending topics due to missing API key.");
    // This is just a fallback for local dev without a key, the main fallback is in api.ts
    return [];
  }

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        systemInstruction: "You are an AI assistant for 'Digital Democracy'. You generate trending topics. Your tone must be neutral and informative. Avoid partisan language.",
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            topics: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  category: { type: Type.STRING },
                  topic: { type: Type.STRING },
                  postCount: { type: Type.NUMBER },
                },
                required: ["category", "topic", "postCount"],
              },
            },
          },
          required: ["topics"],
        },
      },
    });

    const jsonText = response.text.trim();
    const data = JSON.parse(jsonText);

    if (data.topics && Array.isArray(data.topics)) {
      return data.topics;
    } else {
      throw new Error("Received invalid JSON structure for trending topics from Gemini API.");
    }
  } catch (error) {
    console.error("Error generating trending topics with Gemini:", error);
    // On error, the caller (api.ts) should handle fallback to mock data.
    throw new Error("Failed to generate trending topics from Gemini API.");
  }
};